# Generated by Django 6.1 on 2026-08-13 04:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WasteReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Photograph of the reported waste', upload_to='reports/%Y/%m/%d/')),
                ('description', models.TextField(help_text='Detailed description of the waste', max_length=1000)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude coordinate between -90 and 90', max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-90.000000')), django.core.validators.MaxValueValidator(Decimal('90.000000'))])),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude coordinate between -180 and 180', max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-180.000000')), django.core.validators.MaxValueValidator(Decimal('180.000000'))])),
                ('location_name', models.CharField(help_text='Human-readable address or landmark name', max_length=255)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], db_index=True, default='REPORTED', help_text='Current progress status of the report', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the report was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the report was last updated')),
            ],
            options={
                'verbose_name': 'Waste Report',
                'verbose_name_plural': 'Waste Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
